name: eurofarma_treinamento
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  sqflite: ^2.2.0+4
  path: ^1.8.0
  cupertino_icons: ^1.0.2
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.2
  cloud_firestore: ^5.4.3
  shared_preferences: ^2.0.9
  intl: ^0.19.0
  flutter_html: ^3.0.0-alpha.5
  flutter_layout_grid: ^2.0.1
  flutter_math_fork: ^0.7.1
  pdf: ^3.6.0
  open_file: ^3.2.1
  pdf_image_renderer: ^0.6.0
  http: ^0.13.3
  universal_io: ^2.0.4
  flutter_share: ^2.0.0
  path_provider: ^2.0.15
  flutter_html_to_pdf: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true
